site_name: Primate
site_url: https://primatejs.com
repo_name: primatejs/primate
repo_url: https://github.com/primatejs/primate
site_description: JavaScript framework with data verification and server-side rendering
theme:
  font: false
  name: material
  favicon: favicon.ico
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: ayu
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: 'index.md'
  - Modules:
     - 'modules/index.md'
     - Stores:
       - MongoDB: 'modules/stores/mongodb.md'
       - File: 'modules/stores/file.md'
       - JSON: 'modules/stores/json.md'
extra_css:
  - css/extra.css
extra:
  generator: false

